### ISSUE TITLE
Use docker in travis to test building for multiple Ubuntu versions

### ISSUE THREAD

**Issue by fsuarez6** [crigroup/openrave-installation#7]
Using docker in travis we could make sure that this compiles for the supported Ubuntu versions:
- https://docs.travis-ci.com/user/docker/
- https://docs.travis-ci.com/user/build-matrix/

**Comment by nicholasadr** [comment]
I'm learning to implement CI and came across this. What is the advantage of using docker for this repo? Wouldn't something simple like the following do the job?

```
sudo: true
language:
  - generic
cache:
  - apt

jobs:
  include:
    - stage: OpenSceneGraph Trusty
      os: linux
      dist: trusty
      script: ./install-dependencies.sh; ./install-osg.sh
    - stage: OpenRAVE Trusty
      os: linux
      dist: trusty
      script: ./install-dependencies.sh; ./install-fcl.sh; ./install-openrave.sh
    - stage: OpenSceneGraph Xenial
      os: linux
      dist: xenial
      script: ./install-dependencies.sh; ./install-osg.sh
    - stage: OpenRAVE Xenial
      os: linux
      dist: xenial
      script: ./install-dependencies.sh; ./install-fcl.sh; ./install-openrave.sh
    - stage: OpenSceneGraph Bionic
      os: linux
      dist: bionic
      script: ./install-dependencies.sh; ./install-osg.sh
    - stage: OpenRAVE Bionic
      os: linux
      dist: bionic
      script: ./install-dependencies.sh; ./install-fcl.sh; ./install-openrave.sh
```
